// mockData/customer.ts
import { Customer } from '@/types/customer';

export const mockCustomers: Customer[] = [
    {
        basicNumber: "BN001",
        name: "John Smith",
        email: "john.smith@email.com",
        address: "180 Cecil St, Singapore 069546",
        phoneNumber: "65 12341234",
        passport: "KJ1234567",
        customerType: "Individual",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Low",
        lifecycleStatus: "Active",
        lifecycleStatusDate: "2023-06-15"
    },
    {
        basicNumber: "BN002",
        name: "ACME Trading Pte Ltd",
        email: "info@acmetrading.com",
        address: "180 Cecil St, Singapore 069546",
        phoneNumber: "65 12341234",
        passport: "KJ1234568",
        customerType: "PrivateLimited",
        incorporationNumber: "201234567Z",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Low",
        lifecycleStatus: "Active",
        lifecycleStatusDate: "2023-07-01"
    },
    {
        basicNumber: "BN003",
        name: "Sarah Johnson",
        email: "sarah.johnson@email.com",
        address: "12 Marina Blvd, Singapore 018982",
        phoneNumber: "65 23456789",
        passport: "KJ1234569",
        customerType: "Individual",
        registrationCountry: "Singapore",
        isPEP: true,
        riskRating: "Medium",
        lifecycleStatus: "Onboarding",
        lifecycleStatusDate: "2023-11-20"
    },
    {
        basicNumber: "BN004",
        name: "Global Investments Ltd",
        email: "info@globalinvest.com",
        address: "9 Straits View, Singapore 018937",
        phoneNumber: "65 22458890",
        passport: "KJ1234560",
        customerType: "OffshoreCompany",
        incorporationNumber: "BVI123456",
        registrationCountry: "British Virgin Islands",
        isPEP: false,
        riskRating: "High",
        lifecycleStatus: "Suspended",
        lifecycleStatusDate: "2023-10-05"
    },
    {
        basicNumber: "BN005",
        name: "Singapore Holdings Family Trust",
        email: "admin@shfamilytrust.com",
        address: "10 Marina Blvd, Tower 2, #31-01 Marina Bay Financial Centre, 018983",
        phoneNumber: "65 31313131",
        passport: "KJ1234570",
        customerType: "SingaporeTrust",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Medium",
        lifecycleStatus: "Active",
        lifecycleStatusDate: "2023-05-10"
    },
    {
        basicNumber: "BN006",
        name: "CryptoTech Solutions Pte Ltd",
        email: "business@cryptotech.com",
        address: "10 Marina Blvd, Tower 2, #31-01 Marina Bay Financial Centre, 018983",
        phoneNumber: "65 32323232",
        passport: "KJ1234571",
        customerType: "CryptoBusiness",
        incorporationNumber: "202134567K",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "High",
        lifecycleStatus: "Dormant",
        lifecycleStatusDate: "2023-09-20"
    },
    {
        basicNumber: "BN007",
        name: "David Lee Trading",
        email: "d.lee@email.com",
        address: "12 Marina View, Singapore 018961",
        phoneNumber: "65 54908892",
        passport: "KJ1234572",
        customerType: "SoleProprietor",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Low",
        lifecycleStatus: "Active",
        lifecycleStatusDate: "2023-08-15"
    },
    {
        basicNumber: "BN008",
        name: "Cayman Wealth Management Ltd",
        email: "admin@caymanwealth.com",
        address: "6 Shenton Wy, Singapore 068809",
        phoneNumber: "65 67812234",
        passport: "KJ1234573",
        customerType: "OffshoreTrust",
        registrationCountry: "Cayman Islands",
        isPEP: false,
        riskRating: "High",
        lifecycleStatus: "Onboarding",
        lifecycleStatusDate: "2023-11-25"
    },
    {
        basicNumber: "BN009",
        name: "Singapore Public Bank Ltd",
        email: "compliance@sgpbank.com",
        address: "168 Robinson Rd, Singapore 068912",
        phoneNumber: "65 66622246",
        passport: "KJ1234574",
        customerType: "RegulatedEntity",
        incorporationNumber: "199234567D",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Medium",
        lifecycleStatus: "Active",
        lifecycleStatusDate: "2023-04-30"
    },
    {
        basicNumber: "BN010",
        name: "NextGen Technologies Inc",
        email: "contact@nextgentech.com",
        address: "22 Science Park Rd, Singapore 118684",
        phoneNumber: "65 87654321",
        passport: "KJ1234575",
        customerType: "PrivateLimited",
        incorporationNumber: "202234567M",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Low",
        lifecycleStatus: "Prospective",
        lifecycleStatusDate: "2023-11-28"
    },
    {
        basicNumber: "BN011",
        name: "Venture Capital Asia",
        email: "info@vcasia.com",
        address: "80 Robinson Rd, Singapore 068898",
        phoneNumber: "65 99887766",
        passport: "KJ1234576",
        customerType: "PrivateLimited",
        incorporationNumber: "201987654Z",
        registrationCountry: "Singapore",
        isPEP: false,
        riskRating: "Medium",
        lifecycleStatus: "Rejected",
        lifecycleStatusDate: "2023-10-15",
        amlStatus: "Rejected",
        amlNotes: "Failed enhanced due diligence check"
    }
];