name: Node.js CI

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get short SHA and branch name
        id: slug
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create build properties file
        run: |
          cat > scanner_proj/build_prop.txt << EOL
          Branch: ${{ steps.slug.outputs.BRANCH_NAME }}
          Commit: ${{ steps.slug.outputs.SHORT_SHA }}
          Build Date: ${{ steps.slug.outputs.BUILD_DATE }}
          EOL
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: scanner_proj

      - name: Build
        run: npm run build
        working-directory: scanner_proj

      - name: Create deployment zip
        run: |
          cd scanner_proj
          zip -r ../scanner_proj_${{ steps.slug.outputs.SHORT_SHA }}.zip .next public node_modules package.json package-lock.json web.config server.js build_prop.txt

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: scanner_proj_${{ steps.slug.outputs.SHORT_SHA }}
          path: scanner_proj_${{ steps.slug.outputs.SHORT_SHA }}.zip
